;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Field.King.Invalid",NewTagName="Field.Kind.Invalid")
+GameplayTagRedirects=(OldTagName="Field.King.Valid",NewTagName="Field.Kind.Valid")
+GameplayTagRedirects=(OldTagName="Field.King",NewTagName="Field.Kind")
+GameplayTagList=(Tag="Field.Kind.Hide",DevComment="")
+GameplayTagList=(Tag="Field.Kind.Invalid",DevComment="")
+GameplayTagList=(Tag="Field.Kind.Meta",DevComment="")
+GameplayTagList=(Tag="Field.Kind.Start",DevComment="")
+GameplayTagList=(Tag="Field.Kind.Valid",DevComment="")

